### PR TITLE
Fixing a couple of typos and r cmd check complaints

### PR DESCRIPTION
**Pull request by federicomarini**
Hi Nadia,
I took the liberty to dig a bit into the codebase of `goseq`, which as you can remember, [I still very much dig](https://github.com/nadiadavidson/goseq/pull/1) 😄 

I did 
* some fixes to typos I encountered (triggered by reading them as messages in the console)
* a couple of edits to the namespace import directives to have R CMD check not complain about it

Have a look at that and feel free to edit and/or get back to me 😉 

On the same direction - Would you like to bring in some roxygen-based way of documentation and switch to a Rmd-based vignette? Happy to invest some bandwidth into this.

### CODE REVIEW

**Comment by nadiadavidson** [comment]
Hi @federicomarini Thanks for your contribution. However, unfortunately this repo isn't active anymore and you will need to submit pull requests to one that is. I would contact Matthew Young, who is the author and maintainer of goseq, to find out how best to contribute. I'm no longer maintaining the package.

**Comment by federicomarini** [comment]
Sure, just keep me updated on this!

**Comment by nadiadavidson** [comment]
> Sure, just keep me updated on this!

Hi @federicomarini,
You will need to contact Matt Young yourself, as I'm no longer involved in maintaining the package.
All the best,
Nadia.

**Comment by federicomarini** [comment]
Sorry, I misunderstood your "I would contact" 😄 
I'll reach out to him directly!

**Comment by nadiadavidson** [comment]
> Sorry, I misunderstood your "I would contact" 😄 I'll reach out to him directly!

:) Yes sorry about that! I should have been more careful how I wrote it!

**Comment by lshep** [comment]
@nadiadavidson do you by chance know of any better email to contact Matt?  We've been trying to reach out to him directly with the email in the package and he has been unresponsive.   If we cannot get a hold of Matt and you no longer wish to maintainer the package,  would you be okay with granting Federico access to take over maintainership provided he keeps proper accreditation to yourself and Matt?  The failing package is causing a cascading failure effect on packages that dependent on this package.

**Comment by nadiadavidson** [comment]
Hi @lshep and @federicomarini apologies for taking some time to get back to you. I've just contacted Alicia Oshlack who is the senior author of goseq to see what her plans are for maintaining goseq, and can let you know. You could also contact her directly if needed.

**Comment by federicomarini** [comment]
Thanks @nadiadavidson for following up! I will stay tuned for this 😉 
Meanwhile, I did already fix on my two forks the issues for `goseq` and `geneLenDatabase`, just FYI 🎉

**Pull request closed without merging**
